# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/exynos9820-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter beyond0lte beyond1lte beyond2lte beyondx d1 d1x d2s d2x f62,$(TARGET_DEVICE)),)

endif
